[package]
name = "discord-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-rich-presence = "0.1.8"
clap = { version = "3.0.14", features = ["derive"] }